[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
    "-Lnative=.xwin-cache/splat/crt/lib/x86_64",
    "-Lnative=.xwin-cache/splat/sdk/lib/um/x86_64",
    "-Lnative=.xwin-cache/splat/sdk/lib/ucrt/x86_64",
]
