name: Build

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust:
              - nightly
              - 1.70.0
            target: x86_64-unknown-linux-gnu
            binary-name: chatgpt-rs
            archive-name: chatgpt-rs-linux.tar.gz
          - build: macos
            os: macos-latest
            rust:
              - nightly
              - 1.70.0
            target: x86_64-apple-darwin
            binary-name: chatgpt-rs
            archive-name: chatgpt-rs-macos.tar.gz
          - build: windows
            os: windows-latest
            rust:
              - nightly
              - 1.70.0
            target: x86_64-pc-windows-msvc
            binary-name: chatgpt-rs.exe
            archive-name: chatgpt-rs-windows.zip
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies for linux
        if: matrix.build == 'linux'
        run: |
          echo "Running apt-get update"
          sudo apt-get update
          echo "Installing dependencies"
          sudo apt-get install -y pkg-config \
          libclang-dev libgtk-3-dev libxcb-render0-dev \
          libxcb-shape0-dev libxcb-xfixes0-dev  \
          libxkbcommon-dev libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/${{ matrix.binary-name }}"
      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md archive/
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/release/${{ matrix.binary-name }}" ./
            7z a "${{ matrix.archive-name }}" LICENSE README.md ${{ matrix.binary-name }}
          else
            cp "../target/${{ matrix.target }}/release/${{ matrix.binary-name }}" ./
            tar -czf "${{ matrix.archive-name }}" LICENSE README.md ${{ matrix.binary-name }}
          fi
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}
